### ISSUE TITLE
names stop translating after using evac portal

### ISSUE THREAD

**Issue by CadenzaBrillante** [dqx-translation-project/dqxclarity#21]
Occurs with spell or with evac bell. Console gives the line:

2023-01-09 01:02:20.047 | ERROR    | clarity:scan_for_concierge_names:205 - Cannot find DQX process. Must have closed? Exiting.

I thought it was the dialogue as well as I've had this stop working at some point, but can't replicate. It definitely affects the names. Requires restarting the game and dqxclarity in order to restore full functionality

Note that I'm not using Ahkmon. I actually forgot to install it when dqxclarity seemed to cover everything pretty well on its own xD If that or any other thing I've overlooked renders my report moot, I apologize

I don't mind restarting if this happens, but wanted to report in case it's helpful. Thanks!

**Comment by xshobux** [comment]
A few other users have reported this error but I have yet to encounter it myself. I have extra debugging enabled for myself so I can easier diagnose it so I'll keep an eye out.

**Comment by xshobux** [comment]
This is fixed in 3.23.0.
